#!/usr/bin/env node
const fs = require('fs');

const run = () => {
 let postName = process.argv[2];
 createFile(postName);
}

function createFile(postName) {
  let dasherizedName = postName.replace(/\s/g, '-');
  let slug = dasherizedName.toLowerCase();
  let fileName = `${dasherizedName}.md`;

  let date = new Date();

  let month = (date.getMonth() + 1).toString();
  month = month.length < 2 ? `0${month}` : month;

  let year = date.getFullYear();

  let day = date.getDate().toString();
  day = day.length < 2 ? `0${day}` : day;

  let fullPath = `content/posts/${year}-${month}-${day}---${fileName}`;

  fs.writeFile(fullPath, getFileContent(postName, date, slug, fileName), function (err) {
    if (err) throw err;
    console.log(`generated ${fullPath}`);
  });
}

function getFileContent(title, date, slug, fileName) {
  return `---
title: "${title}"
date: "${date.toISOString()}"
template: "post"
draft: true
slug: "/posts/${slug}/"
category: "Engineering"
banner: ""
filename: "${fileName}"
tags:
  - ""
description: "DESCRIPTION HERE"
---`;
}


run();
